### PR TITLE
Add multiple double tap

### PR DESCRIPTION
**Pull request by ccabrol**

### CODE REVIEW

**Comment by mister-ben** [comment]
Thanks. With this a single tap (after the initial tap to activate the overlay), given a `seekSeconds` of `10`, will seek 10 seconds, another tap another 20 seconds, a third tap another 30 seconds and so on. So three taps in quick succession would advance 60 seconds. Is the the intention?

The tests failing is because of linting. Running `npm run lint` will show the errors according to the project's style conventions.

**Comment by ccabrol** [comment]
> Thanks. With this a single tap (after the initial tap to activate the overlay), given a `seekSeconds` of `10`, will seek 10 seconds, another tap another 20 seconds, a third tap another 30 seconds and so on. So three taps in quick succession would advance 60 seconds. Is the the intention?
> 
> The tests failing is because of linting. Running `npm run lint` will show the errors according to the project's style conventions.

Not really, the intention was to double tap for seeking 10 seconds, and another double tab to seek 20 seconds, another 30 seconds more etc. But, if I check youtube, it works like you described. I'll try to mimic youtube...

**Comment by mister-ben** [comment]
Thanks, it makes more sense like this.

I noticed a problem though in that all taps need to be within the timeout, or it can end up triggering when `this.nbtap` is 0, resulting in a seek in the wrong direction. I guess the the taps would need to be handled by a debounce rather than a simple timeout.

**Comment by mister-ben** [comment]
Closing in favour of #82. Thanks for the suggestion!

**Pull request closed without merging**
